//DEFINIMOS SI ES HTTP O HTTPS
var HIPERTEXT ="http://";
//OBTIENE EL NOMBRE DE HOST Y PUERTO
var SERVER_NAME = window.location.host;
//DEFINIMOS EL NOMBRE DEL PROYECTO
var PROYECT_NAME = "sismedico";
//DEFINIMOS EL SEPARADOR DE LAS RUTAS
var SEPARATOR = "/";
//DEFINIMOS LA URL GENERAL DEL SISTEMA
var URL_MAIN = HIPERTEXT+SERVER_NAME + SEPARATOR + PROYECT_NAME + SEPARATOR;
//DEFINIMOS LA URL DONDE SE ENCUENTRAN LOS ARCHIVOS TEMPORALES
var URL_TEMPORAL = URL_MAIN + "tmp" + SEPARATOR;
//DEFINIMOS LA URL DEL TEMPLATE GENERAL 
var URL_TEMPLATE = URL_MAIN+"img/dashboard/";
//SE ESPERA MAS DEFINICIONES
var URL_IMG = URL_MAIN+"img/";